[package]
name = "rusty_inference"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
candle-core = { version = "0.9.1", features = ["metal"] }
candle-nn = "0.9.1"
candle-transformers = "0.9.1"
safetensors = "0.6.2"
tokenizers = "0.22.1"
